apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Use the AWX operator config for this version
  - github.com/ansible/awx-operator/config/default?ref=2.17.0

images:
  - name: quay.io/ansible/awx-operator
    newTag: 2.17.0

# Install everything into the awx namespace
namespace: awx
