---
- name: "Chocolatey"
  hosts: "{{ group_1 }}"
  vars:
    ansible_connection: winrm
    #ansible_password: "{{ password }}"
    ansible_port: 5985
    #ansible_user: "{{ user_id }}"
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_transport: ntlm

  tasks:
    - name: Install chocolatey
      win_chocolatey:
          name: 
           - chocolatey
           - chocolatey-core.extension
          state: present
