---
- name: Install All updates and report back
  hosts: "{{ group_1 }}"
  vars:
    ansible_connection: winrm
    ansible_user: "{{ user_id }}"
    ansible_password:  "{{ password }}"
    ansible_winrm_transport: credssp
    ansible_port: 5985
    ansible_winrm_server_cert_validation: ignore
  
  tasks:
  
  - name: Pause for 5 minutes to build app cache
    pause:
      minutes: 3
  - name: Install All updates
    win_updates:
     category_names:
       - SecurityUpdates
       - CriticalUpdates
       - UpdateRollups
       - Application
       - DefinitionUpdates
       - FeaturePacks
       - ServicePacks
       - Tools
       - UpdateRollups
       - Updates
       - Drivers
     log_path: C:\ansible_installed_Updates.txt
     reboot: yes
     reboot_timeout: 5400
...
