---
- name: Install All updates and report back
  hosts: "{{ group_1 }}"
  vars:
    ansible_connection: winrm
    ansible_user: "{{ user_id }}"
    ansible_password:  "{{ password }}"
    ansible_become_user: "{{ user_id }}"
    ansible_become_pass: "{{ password }}"
    ansible_winrm_transport: ntlm
    ansible_port: 5985
    ansible_winrm_server_cert_validation: ignore

  tasks:
      
  - name: Remove IE feature from machine
    win_shell: powershell.exe -executionpolicy bypass -noninteractive -nologo Disable-WindowsOptionalFeature -FeatureName Internet-Explorer-Optional-amd64 â€“Online -Force
    become: yes
    become_user: "{{ user_id }}"
    become_method: runas
