--- 
- 
  hosts: "{{ group_1 }}"
  name: "Reboot Windows Hosts"
  tasks:
    - name: "Restart Windows host with personalized settingd"
      win_reboot: 
        msg: "Reboot initiated by remote admin"
        pre_reboot_delay: 5
        reboot_timeout: 5900
  vars: 
    ansible_connection: winrm
    ansible_user: "{{ user_id }}"
    ansible_password: "{{ password }}"
    ansible_port: 5985
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_transport: credssp
