ms_builtins:
  install_languages:
    name: InstallLanguages
    uri: https://raw.githubusercontent.com/Azure/RDS-Templates/master/CustomImageTemplateScripts/CustomImageTemplateScripts_2024-03-27/InstallLanguagePacks.ps1

  set_default_os_language:
    name: SetDefaultOSLanguage
    uri: https://raw.githubusercontent.com/Azure/RDS-Templates/master/CustomImageTemplateScripts/CustomImageTemplateScripts_2024-03-27/SetDefaultLang.ps1

  time_zone_redirection:
    name: TimeZoneRedirection
    uri: https://raw.githubusercontent.com/Azure/RDS-Templates/master/CustomImageTemplateScripts/CustomImageTemplateScripts_2024-03-27/TimezoneRedirection.ps1

  disable_storage_sense:
    name: DisableStorageSense
    uri: https://raw.githubusercontent.com/Azure/RDS-Templates/master/CustomImageTemplateScripts/CustomImageTemplateScripts_2024-03-27/DisableStorageSense.ps1

  install_fslogix:
    name: InstallFSLogix
    uri: https://raw.githubusercontent.com/Azure/RDS-Templates/master/CustomImageTemplateScripts/CustomImageTemplateScripts_2024-03-27/FSLogix.ps1

  configure_rdp_shortpath:
    name: ConfigureRDPShortpath
    uri: https://raw.githubusercontent.com/Azure/RDS-Templates/master/CustomImageTemplateScripts/CustomImageTemplateScripts_2024-03-27/RDPShortpath.ps1

  install_multimedia_redirection:
    name: InstallMultimediaRedirection
    uri: https://raw.githubusercontent.com/Azure/RDS-Templates/master/CustomImageTemplateScripts/CustomImageTemplateScripts_2024-03-27/MultiMediaRedirection.ps1

  remove_microsoft_office_applications:
    name: RemoveOffice
    uri: https://raw.githubusercontent.com/Azure/RDS-Templates/master/CustomImageTemplateScripts/CustomImageTemplateScripts_2024-03-27/ConfigureOfficeApps.ps1

  apply_windows_updates:
    name: ApplyWindowsUpdates
    uri: https://raw.githubusercontent.com/Azure/RDS-Templates/master/CustomImageTemplateScripts/CustomImageTemplateScripts_2024-03-27/ApplyWindowsUpdates.ps1

  enable_screen_capture_protection:
    name: EnableScreenCaptureProtection
    uri: https://raw.githubusercontent.com/Azure/RDS-Templates/master/CustomImageTemplateScripts/CustomImageTemplateScripts_2024-03-27/ScreenCaptureProtection.ps1

  configure_session_timeouts:
    name: ConfigureSessionTimeouts
    uri: https://raw.githubusercontent.com/Azure/RDS-Templates/master/CustomImageTemplateScripts/CustomImageTemplateScripts_2024-03-27/ConfigureSessionTimeoutsV2.ps1

  configure_windows_optimizations:
    name: ConfigureWindowsOptimizations
    uri: https://raw.githubusercontent.com/Azure/RDS-Templates/master/CustomImageTemplateScripts/CustomImageTemplateScripts_2024-03-27/WindowsOptimization.ps1
